-- Create the audit log table for exclusion actions
CREATE TABLE IF NOT EXISTS DEV_ALPHATEL.PRESENTATION.MLM_EXCLUSION_AUDIT_LOG (
  ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
  REFEREE_LOGIN VARCHAR(255) NOT NULL,
  ACTION_TYPE VARCHAR(50) NOT NULL,
  ACTION_BY VARCHAR(255) NOT NULL,
  ACTION_DETAILS TEXT,
  PREVIOUS_STATE TEXT,
  NEW_STATE TEXT,
  ACTION_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (ID)
);

-- Add comments for documentation
COMMENT ON TABLE DEV_ALPHATEL.PRESENTATION.MLM_EXCLUSION_AUDIT_LOG IS 'Tracks all changes to the exclusion list for audit purposes';
COMMENT ON COLUMN DEV_ALPHATEL.PRESENTATION.MLM_EXCLUSION_AUDIT_LOG.ID IS 'Unique identifier for the audit log entry';
COMMENT ON COLUMN DEV_ALPHATEL.PRESENTATION.MLM_EXCLUSION_AUDIT_LOG.REFEREE_LOGIN IS 'Username of the referee being excluded';
COMMENT ON COLUMN DEV_ALPHATEL.PRESENTATION.MLM_EXCLUSION_AUDIT_LOG.ACTION_TYPE IS 'Type of action performed (CREATE, UPDATE, DELETE)';
COMMENT ON COLUMN DEV_ALPHATEL.PRESENTATION.MLM_EXCLUSION_AUDIT_LOG.ACTION_BY IS 'Username of the user who performed the action';
COMMENT ON COLUMN DEV_ALPHATEL.PRESENTATION.MLM_EXCLUSION_AUDIT_LOG.ACTION_DETAILS IS 'Description of what was changed';
COMMENT ON COLUMN DEV_ALPHATEL.PRESENTATION.MLM_EXCLUSION_AUDIT_LOG.PREVIOUS_STATE IS 'State of the exclusion record before the change';
COMMENT ON COLUMN DEV_ALPHATEL.PRESENTATION.MLM_EXCLUSION_AUDIT_LOG.NEW_STATE IS 'State of the exclusion record after the change';
COMMENT ON COLUMN DEV_ALPHATEL.PRESENTATION.MLM_EXCLUSION_AUDIT_LOG.ACTION_DATE IS 'Date and time when the action was performed'; 